### ISSUE TITLE
feat: support multi circuits

### ISSUE THREAD

**Issue by lispc** [fluidex/prover-cluster#101]
at least we have circuits of different tx num. block_8 block_16 block_512 etc.

Maybe we need to support exit circuit in the future

**Comment by HAOYUatHZ** [comment]
1. change https://github.com/fluidex/prover-cluster/blob/master/proto/cluster.proto `Circuit` type to string.
2. fix the types in src/client/grpc_client.rs, src/client/prover.rs, src/coordinator/controller.rs accordingly.
