### ISSUE TITLE
TODO: witness generator

### ISSUE THREAD

**Issue by HAOYUatHZ** [Fluidex/prover-cluster#28]

**Comment by lispc** [comment]
Call the circuit cpp binary？

**Comment by HAOYUatHZ** [comment]
Yes we may need to schedule some workers for this.

**Comment by HAOYUatHZ** [comment]
also related: https://github.com/Fluidex/prover-cluster/issues/4

**Comment by HAOYUatHZ** [comment]
closed via https://github.com/Fluidex/prover-cluster/pull/44
